---
- name: create textfile_collector
  ansible.builtin.file:
    path: "{{ node_exporter_default_dir }}/textfile_collector"
    state: directory

- name: download node_exporter
  ansible.builtin.get_url:
    url: "{{ node_exporter_download_url }}"
    dest: /tmp/node_exporter.tar.gz

- name: unarchive package
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/

- name: rename directory
  ansible.builtin.copy:
    src: "{{ node_exporter_default_dir }}-{{ node_exporter_version }}/"
    dest: "{{ node_exporter_default_dir }}"
    remote_src: yes

- name: remove old directory
  ansible.builtin.file:
    path: "{{ node_exporter_default_dir }}-{{ node_exporter_version }}"
    state: absent

- name: create node_exporter service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: create node_exporter.socket service
  ansible.builtin.template:
    src: node_exporter.socket.j2
    dest: /etc/systemd/system/node_exporter.socket

- name: start node_exporter
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: node_exporter
    enabled: yes
